### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [OpticksSecurity/gtm-conversions-template#1]
https://github.com/OpticksSecurity/gtm-conversions-template/blob/8e7d707cfd8341d183c28505f06f9bd78dc1ea7f/template.tpl#L79

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by aserrabl** [comment]
Hi @semisight, thank you for pointing it out. We have corrected the mentioned issue and we are now using encodeUriComponent: https://github.com/OpticksSecurity/gtm-conversions-template/commit/400fb345c8efae82017936c15a8d7e77c1d662d5
